### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by leeyome** [carlniger/acitool#21]
Hi.

I'd like to use this tool, and installed on windows 10 / python3.6... tried to run, but not work.
-----------------------------------------------------------
C:\Users\User02\AppData\Local\Programs\Python\Python36\Lib\site-packages\acitool>python main.py
Please enter the path to aci_deploy_master-public.xls, note that this is also where the workbook will be saved upon completion.
Path: C:\Users\User02\AppData\Local\Programs\Python\Python36\Lib\site-packages\acitool
Enter the APIC IP: 1.1.1.1
Enter APIC username: admin
Enter APIC password:
Workbook Loaded.
A snapshot including 'acipdt_backup' already exists. Would you like to delete this snapshot or exit?
Delete 'd' or Exit 'q' [q]: d
Snapshot taken successfully, continuing.
********************************************************************************
Starting work on Fabric Pod Policies section
********************************************************************************
Deploying line 6 from section Fabric Pod Policies...
Traceback (most recent call last):
  File "main.py", line 454, in <module>
    main()
  File "main.py", line 439, in main
    pod_policies(apic, cookies, wb, wr_wb)
  File "main.py", line 159, in pod_policies
    status = eval("podpol.%s(**var_dict[pos])" % func)
  File "<string>", line 1, in <module>
  File "C:\Users\User02\AppData\Local\Programs\Python\Python36\lib\site-packages\acitool\acipdt.py", line 148, in comission_hw
    templateVars = process_kwargs(required_args, optional_args, **kwargs)
  File "C:\Users\User02\AppData\Local\Programs\Python\Python36\lib\site-packages\acitool\acipdt.py", line 30, in process_kwargs
    raise InsufficientArgs('Insufficient required arguments.')
acitool.acipdt.InsufficientArgs: Insufficient required arguments.
-------------------------------------------
excel sheet was no data..
I tried to add some data (ntp, tenant..) but it's same.
What is the problems?

ACI version is 3.0

Thanks.

**Comment by carlmontanari** [comment]
Either input data for all fields or remove the function name from column A. If you leave the function name in column A with no data it will fail (because it tries to parse "empty" data which will basically show up as an empty string for a required argument -- hence the exception raised). The parsing of the excel sheet is not very robust so you have to be ginger with it.

**Comment by leeyome** [comment]
Thank you for your help. ^^
