### ISSUE TITLE
Insights about Fabric Access polices

### ISSUE THREAD

**Issue by lacheron** [carlniger/acitool#25]
Hello Carl, 

I hope you are doing well, i have a little problem to understand the creation of the fabric access policies
like the interface policy groups, i can create the policies one by one, but if how can i create th groups, i tried with created and created,modified and should i fullfil all the parameters in the policy groups

[aci_deploy.zip](https://github.com/carlniger/acipdt/files/2094810/aci_deploy.zip)

**Comment by carlmontanari** [comment]
Hello!

You can simply add a row below your existing row and fill it with the data you need. I've added a line below your Policy Group to demonstrate (think line 116), let me know if that makes sense.

Carl
[aci_deploy.xls.zip](https://github.com/carlniger/acipdt/files/2094975/aci_deploy.xls.zip)

**Comment by lacheron** [comment]
Hello carl, thanks for your post, but what i mean at the first time if can i create a policy group without all the objects, but i started to read, and i think no, so i can only created without the ppv and storm, but all the paramers are required?

def int_pol_grp_access(self, **kwargs):
        required_args = {'name': '',
                         'status': '',
                         'lldp': '',
                         'cdp': '',
                         'aep': '',
                         'mcp': '',
                         'link': ''}
        optional_args = {'ppv': '',
                         'storm': ''}

**Comment by lacheron** [comment]
i tried to do the example, i created the policy but the script stopped at the interface policy group
how can i overcome that?
thanks for your time Carl!

[aci_deploy.zip](https://github.com/carlniger/acipdt/files/2095358/aci_deploy.zip)


![c1](https://user-images.githubusercontent.com/33548771/41309567-1c58703e-6e4d-11e8-96c2-b545804b2164.PNG)

**Comment by carlmontanari** [comment]
Yep, you are correct, all of those parameters are required. Obviously they wouldn't be required by ACI itself, but they are in the script. I *think* that most if not all of the arguments that are optional (via PDT) are listed in the spreadsheet. They are for sure listed in the code itself -- if you search the acipdt.py file for the name of the function you are using (int_pol_grp_access) as you outlined in the previous comment you can see what is optional and required.

If there is a requirement feel free to open a PR and we can merge in making more things optional, hope that helps!

**Comment by lacheron** [comment]
Hi Carl, i was able to create the access policies, thanks a lot carl for your help, whatever thing i ask you again you have made an awesome work with that, thanks!
