### ISSUE TITLE
Use dict instead of Jinja?

### ISSUE THREAD

**Issue by Paraidomat** [carlniger/acitool#27]
https://github.com/carlniger/acipdt/blob/b6da76c60c86419497188b76595d317549377d2e/acipdt/acipdt.py#L92

Hi,

I was scrolling through the code and thought to myself: "Why isn't he just using a dict in the first place?"

```python
    def login(self):
        # Load login json payload
        payload = '''
        {{
            "aaaUser": {{
                "attributes": {{
                    "name": "{user}",
                    "pwd": "{pword}"
                }}
            }}
        }}
        '''.format(user=self.user, pword=self.pword)  # This creates a string
        payload = json.loads(payload,  # This parses the string to a dict
                             object_pairs_hook=collections.OrderedDict)
```

Is there any specific reason for this, instead of using this:

```python
def login(self):
    # Load login json payload
    payload = dict()
    payload = { 
        'aaaUser': { 
            'attributes': { 
                'name': self.user, 
                'pwd': self.pword 
            }
        }
    }
    # And so on...
```

Just wondering :)

**Comment by carlmontanari** [comment]
Hello! I did use dicts to start with, but prior to 3.7(or maybe 3.6?) dicts were unordered so sometimes the  payload would get all screwed up and break things. Also, keeping all the Jinja stuff out of the main code helps with readability IMO. I suppose you could easily enough use a dict on modern Python, but at this point there is no going back :)

**Comment by Paraidomat** [comment]
Ah okay, I was just wondering. Is the API really that sensitive, that the order of the attributes is a thing?

Thanks for your insight :)

**Comment by carlmontanari** [comment]
I think it would probably be fine (as in the API is not *that* sensitive) *if* I didnt do some bad things. Early days of this utility I had a lot of objects looped together (and some still are) so that if the dict was unordered a Subnet may get created before a  Bridge Domain for example, which would obviously break stuff. So, its definitely partly my fault :)

I'll close this now, thanks for the question, let me know if anything else pops up

**Comment by Paraidomat** [comment]
Okay, thanks for this tool, @carlniger ... I will test it out in the next few days 👍
